const APP = {
  DELETE_SETTING: "DELETE_SETTING",
  GET_SETTING: "GET_SETTING",
  GET_RECENT_PROJECTS: "GET_RECENT_PROJECTS",
  LOAD_APPLICATION_STATE: 'LOAD_APPLICATION_STATE',
  LOAD_APPLICATION_STATE_FULFILLED: 'LOAD_APPLICATION_STATE_FULFILLED',
  LOAD_APPLICATION_STATE_PENDING: 'LOAD_APPLICATION_STATE_PENDING',
  LOAD_APPLICATION_STATE_REJECTED: 'LOAD_APPLICATION_STATE_REJECTED',
  SAVE_SETTINGS: "SAVE_SETTINGS",
  UPDATE_SETTING: "UPDATE_SETTING",
  UPDATE_RECENT_PROJECTS: "UPDATE_RECENT_PROJECTS",
};

const LIBRARY = {
  ADD_FILE: "LIBRARY_ADD_FILE",
  ADD_TAG: "LIBRARY_ADD_TAG",
  DELETE_FILE: "LIBRARY_DELETE_FILE",
  DELETE_TAG: "LIBRARY_DELETE_TAG",
  GET_FILES: "LIBRARY_GET_FILES",
  GET_TAGS: "LIBRARY_GET_TAGS",
  LOAD_INDEX: "LIBRARY_LOAD_INDEX",
  REINDEX: 'LIBRARY_REINDEX',
  UPDATE_FILE: "LIBRARY_UPDATE_FILE",
  UPDATE_INDEX: "LIBRARY_UPDATE_INDEX",
  UPDATE_TAG: "LIBRARY_UPDATE_TAG",
  WRITE_INDEX: "LIBRARY_WRITE_INDEX",
};

const PROFILE = {
  LOAD_PROFILE: "PROFILE_LOAD",
  UPDATE_PROFILE: "PROFILE_UPDATE",
  WRITE_PROFILE: "PROFILE_WRITE",
};

const PROJECT = {
  ADD_FILE: "PROJECT_ADD_FILE",
  ADD_TAG: "PROJECT_ADD_TAG",
  CLONE_PROJECT: "PROJECT_CLONE",
  CREATE_PROJECT: "PROJECT_CREATE",
  DELETE_FILE: "PROJECT_DELETE_FILE",
  DELETE_TAG: "PROJECT_DELETE_TAG",
  GET_FILES: "PROJECT_GET_FILES",
  GET_TAGS: "PROJECT_GET_TAGS",
  UPDATE_FILE: "PROJECT_UPDATE_FILE",
  UPDATE_TAG: "PROJECT_UPDATE_TAG",
  WRITE_INDEX: "PROJECT_WRITE_INDEX",
};

export { APP, LIBRARY, PROFILE, PROJECT };
