const APP = {
  DELETE_SETTING: 'DELETE_SETTING',
  GET_SETTING: 'GET_SETTING',
  GET_RECENT_PROJECTS: 'GET_RECENT_PROJECTS',
  LOAD_APPLICATION_STATE: 'LOAD_APPLICATION_STATE',
  LOAD_APPLICATION_STATE_FULFILLED: 'LOAD_APPLICATION_STATE_FULFILLED',
  LOAD_APPLICATION_STATE_PENDING: 'LOAD_APPLICATION_STATE_PENDING',
  LOAD_APPLICATION_STATE_REJECTED: 'LOAD_APPLICATION_STATE_REJECTED',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  SHOW_MODAL: 'SHOW_MODAL',
  UPDATE_SETTING: 'UPDATE_SETTING',
  UPDATE_RECENT_PROJECTS: 'UPDATE_RECENT_PROJECTS'
};

const LIBRARY = {
  ADD_FILE: 'LIBRARY_ADD_FILE',
  ADD_TAG: 'LIBRARY_ADD_TAG',
  DELETE_FILE: 'LIBRARY_DELETE_FILE',
  DELETE_TAG: 'LIBRARY_DELETE_TAG',
  GET_FILES: 'LIBRARY_GET_FILES',
  GET_TAGS: 'LIBRARY_GET_TAGS',
  LOAD_INDEX: 'LIBRARY_LOAD_INDEX',
  LOAD_INDEX_FULFILLED: 'LIBRARY_LOAD_INDEX_FULFILLED',
  LOAD_INDEX_PENDING: 'LIBRARY_LOAD_INDEX_PENDING',
  LOAD_INDEX_REJECTED: 'LIBRARY_LOAD_INDEX_REJECTED',
  UPDATE: 'UPDATE',
  UPDATE_FILE: 'LIBRARY_UPDATE_FILE',
  UPDATE_INDEX: 'LIBRARY_UPDATE_INDEX',
  UPDATE_INDEX_FULFILLED: 'LIBRARY_UPDATE_INDEX_FULFILLED',
  UPDATE_INDEX_PENDING: 'LIBRARY_UPDATE_INDEX_PENDING',
  UPDATE_INDEX_REJECTED: 'LIBRARY_UPDATE_INDEX_REJECTED',
  UPDATE_TAG: 'LIBRARY_UPDATE_TAG',
  WRITE_INDEX: 'LIBRARY_WRITE_INDEX',
  WRITE_INDEX_FULFILLED: 'LIBRARY_WRITE_INDEX_FULFILLED',
  WRITE_INDEX_PENDING: 'LIBRARY_WRITE_INDEX_PENDING',
  WRITE_INDEX_REJECTED: 'LIBRARY_WRITE_INDEX_REJECTED'
};

const PROFILE = {
  LOAD_PROFILE: 'PROFILE_LOAD',
  LOAD_PROFILE_FULFILLED: 'PROFILE_LOAD_FULFILLED',
  LOAD_PROFILE_PENDING: 'PROFILE_LOAD_PENDING',
  LOAD_PROFILE_REJECTED: 'PROFILE_LOAD_REJECTED',
  UPDATE_PROFILE: 'PROFILE_UPDATE',
  WRITE_PROFILE: 'PROFILE_WRITE',
  WRITE_PROFILE_FULFILLED: 'PROFILE_WRITE_FULFILLED',
  WRITE_PROFILE_PENDING: 'PROFILE_WRITE_PENDING',
  WRITE_PROFILE_REJECTED: 'PROFILE_WRITE_REJECTED'
};

const PROJECT = {
  ADD_FILE: 'ADD_PROJECT_FILE',
  ADD_RECENT_PROJECT: 'ADD_RECENT_PROJECT',
  ADD_TAG: 'ADD_PROJECT_TAG',
  CLONE_PROJECT: 'CLONE_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  DELETE_FILE: 'DELETE_PROJECT_FILE',
  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_TAG: 'DELETE_PROJECT_TAG',
  LOAD_PROJECT: 'LOAD_PROJECT',
  REMOVE_RECENT_PROJECT: 'REMOVE_RECENT_PROJECT',
  UPDATE_FILE: 'UPDATE_PROJECT_FILE',
  UPDATE_INDEX: 'UPDATE_PROJECT_INDEX',
  UPDATE_TAG: 'UPDATE_PROJECT_TAG'
};

export { APP, LIBRARY, PROFILE, PROJECT };
