export default {
  DELETE_SETTING: 'DELETE_SETTING',
  GET_SETTING: 'GET_SETTING',
  GET_RECENT_PROJECTS: 'GET_RECENT_PROJECTS',
  LOAD_APPLICATION_STATE: 'LOAD_APPLICATION_STATE',
  LOAD_APPLICATION_STATE_FULFILLED: 'LOAD_APPLICATION_STATE_FULFILLED',
  LOAD_APPLICATION_STATE_PENDING: 'LOAD_APPLICATION_STATE_PENDING',
  LOAD_APPLICATION_STATE_REJECTED: 'LOAD_APPLICATION_STATE_REJECTED',
  QUIT: 'QUIT',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  SHOW_ABOUT: 'SHOW_ABOUT',
  SHOW_MODAL: 'SHOW_MODAL',
  SHOW_PREFERENCES: 'SHOW_PREFERENCES',
  UPDATE_SETTING: 'UPDATE_SETTING',
  UPDATE_RECENT_PROJECTS: 'UPDATE_RECENT_PROJECTS'
};
