export default {
  LOAD_PROFILE: 'PROFILE_LOAD',
  LOAD_PROFILE_FULFILLED: 'PROFILE_LOAD_FULFILLED',
  LOAD_PROFILE_PENDING: 'PROFILE_LOAD_PENDING',
  LOAD_PROFILE_REJECTED: 'PROFILE_LOAD_REJECTED',
  UPDATE_PROFILE: 'PROFILE_UPDATE',
  WRITE_PROFILE: 'PROFILE_WRITE',
  WRITE_PROFILE_FULFILLED: 'PROFILE_WRITE_FULFILLED',
  WRITE_PROFILE_PENDING: 'PROFILE_WRITE_PENDING',
  WRITE_PROFILE_REJECTED: 'PROFILE_WRITE_REJECTED'
};
