export default {
  ADD_FILE: 'REPO_ADD_FILE',
  ADD_FILES: 'REPO_ADD_FILES',
  COMMIT: 'REPO_COMMIT',
  GET_CONFIG: 'REPO_GET_CONFIG',
  GET_LOG: 'REPO_GET_LOG',
  REMOVE_FILE: 'REPO_REMOVE_FILE',
  PULL: 'REPO_PULL',
  PUSH: 'REPO_PUSH',
  SET_CONFIG: 'REPO_SET_CONFIG',
};
